[package]
name = "fpga_core"
version = "0.1.0"
edition = "2024"

[dependencies]
rhdl = { git = "https://github.com/Pfat8EqualsD/rhdl", branch = "main" }
rhdl-fpga = { git = "https://github.com/Pfat8EqualsD/rhdl", branch = "main" }
anyhow = "1.0"
miette = "7.6.0"